### ISSUE TITLE
pathContext Deprecated 

### ISSUE THREAD

**Issue by ahmad-reza619** [akzhy/gatsby-starter-elemental#12]
![Screen Shot 2020-03-07 at 22 55 50](https://user-images.githubusercontent.com/52902060/76146616-cc8ff900-60c6-11ea-8a80-1de3a166b764.png)

I'm happy to open a PR for this 😄

**Comment by akzhy** [comment]
Hey @ahmad-reza619 feel free to open a pr. I will merge it 😊
