### ISSUE TITLE
Comment for blog post

### ISSUE THREAD

**Issue by ahmad-reza619** [akzhy/gatsby-starter-elemental#14]
### Problems

currently there is no way to add comments in a blog post, it would be nice to add that kind of feature. Since it maybe would attract more people to user's site, and also interactivity of the sites.

### Solution

Maybe we can add [this](https://www.gatsbyjs.org/packages/gatsby-plugin-disqus/) plugin so that there will be support for comments

Let me know what you think 😄

**Comment by akzhy** [comment]
Hey @ahmad-reza619 , that would be a great implementation. I will add it as soon as I can. If you're interested feel free to add it.

**Comment by ahmad-reza619** [comment]
i will work on the PR tonight 😄
