### ISSUE TITLE
Firefox Dark Mode Switch in footer

### ISSUE THREAD

**Issue by s1z5d** [akzhy/gatsby-starter-elemental#17]
I'm using Firefox on Ubuntu 18.04 and the dark mode switch is being displayed as follows on the footer:
![image](https://user-images.githubusercontent.com/16429948/76681209-99101a00-6644-11ea-9889-af13a96cbd3c.png)

Also, out of curiosity - how does this not happen on Chrome? I couldn't find any code that turns off the switch on the footer.

Thanks :D

**Comment by akzhy** [comment]
Hey @siddhantvirmani, thanks for pointing this out. It has just been fixed in #18
