### ISSUE TITLE
Can't resize window 

### ISSUE THREAD

**Issue by acstott** [akzhy/gatsby-starter-elemental#21]
TypeError on resizing window:

TypeError: this.setState is not a function. (In 'this.setState({
      winHeight: window.innerHeight
    })', 'this.setState' is undefined)

**Comment by acstott** [comment]
I fixed the issue, having trouble pushing a feature branch for PR for you to review - do I need to be added as a contributor to do so?

**Comment by akzhy** [comment]
Hi @acstott, you should be able to create a PR, fork the repo, apply changes on the forked repo and then create a PR
