### ISSUE TITLE
How can I change the link from /portfolio to /projects?

### ISSUE THREAD

**Issue by arshiuh** [akzhy/gatsby-starter-elemental#24]
What files would I have to change the URL for each of the NavLinks?

**Comment by akzhy** [comment]
Hey @arshiuh there are a couple of changes that you have to make.

First rename the `portfolio` folder in `contents` to projects.

Replace `portfolio` with `projects`  on these files
`gatsby-node.js`, on lines 67, 130
`src/components/list-portfolio.js`, line 9
`src/templates/portfolio-list.js`, line 21,43
