### ISSUE TITLE
Relative paths in Markdown Frontmatter?

### ISSUE THREAD

**Issue by hrishikesh-k** [akzhy/gatsby-starter-elemental#28]
Hello.

This isn't really an issue, but, more of a personal preference. I was wondering, if I could store all the images (and videos) used in the blog and/or portfolio in their respective directories in the `static` folder for better organization of all media files in just one folder. I tried doing it and it works correctly for media inside the Markdown content, however, the images in `Frontmatter` work only when they're in the same folder as the `index.md`.

I tried using the following paths in `Frontmatter` after storing the files in correct folder inside `static`:

`image: /images/cover.png` - hoping it would load the image from root of the domain. This didn't work.

`image: ../../../static/images/cover.png` - a complete relative path of the image according to the location of `index.md`. This didn't work either.

In both the cases, I get `TypeError: Cannot read property 'childImageSharp' of null` in browser.

Further, it points to the file `src/components/items-portfolio.js:13`

```
<div className="item col s12">
  11 | 	<div className="row flex">
  12 | 		<div className="col m6 image">
> 13 | 			<Img fluid=
  14 | 				{
  15 | 					this.props.data.node.frontmatter.image.childImageSharp.fluid
  16 | 				}/>
```
Currently, my website and everything is working fine, so, this can be safely ignored if it's not considered worth thinking upon. It currently just bugs me a little that it's not all in one folder. 😉

**Comment by akzhy** [comment]
Hey,
To add images from static folder, you can simply use `/images/imagename`, but please note that this method is really disadvantageous because if you source images from the static folder, there won't be a blur up preview or screen resolution based images. It is better to use the conventional method.

**Comment by hrishikesh-k** [comment]
Hello.

I tried it even before and now, again. The path `/images/imagename` doesn't work, however, I see what you say. Even though I'm not a fan of those blurred up images, the resolution based images are kinda important. I just had to use it because I had to use site logo from static folder, so, I thought, why create a copy.

**Comment by akzhy** [comment]
To use in frontmatter you will have to change some queries, but this will break all the other images that are not in the static folder. I would say making a copy will be better for the long run for the users of your site.

**Comment by hrishikesh-k** [comment]
I've now taken a full backup. If I may ask, which queries would they be?

**Comment by akzhy** [comment]
There are a couple of files you will have to change, you will basically have to replace

```
image {
    publicURL
    childImageSharp {
        fluid(maxWidth: 1920) {
            srcSet
            ...GatsbyImageSharpFluid
       }
    }
}
``` 

with 
```
image
```

This will simply retrieve the URL as it is given (without gatsby manipulations) and then you will have to replace `gatsby-image` `<Img>` component with the normal `<img>` component.

The queries are located at `src/components` in the files `list-` and `src/templates/list-`
The component is at `src/components` in the files `item-` 

`list-` => `list-portfolio.js` and `list-blog.js`

**Comment by hrishikesh-k** [comment]
It seemed an easy task, but, this error pops-up: `Field "image" of type "File" must have a selection of subfields. Did you mean "image { ... }"?`

**Comment by akzhy** [comment]
Hey, It probably means that you have some image that is still using the conventional method somewhere. For static to work, you will have to make sure that all of the images (in all pages) are in the static folder.

**Comment by hrishikesh-k** [comment]
It was the case before, but, now, I replaced all image paths in all pages in the `contents` folder. Unfortunately, the same error exists.

**Comment by akzhy** [comment]
Try `gatsby clean`

**Comment by hrishikesh-k** [comment]
That worked. At first, it gave a lot of errors in various files in `templates` folder, but, I went ahead and tried to fix them all. Then, the images had lost their size styling, but, I added some CSS which fixed that. Great work sir, great template, everything just amazing. Thank you!
