### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by baart1989** [akzhy/gatsby-starter-elemental#29]
Hello @akzhy 

This repo is great starter, far best I ever seen.
Also it uses tailwind which is super cool! 
The code looks neat and clean!

I was thinking what is the best way to thank you for this awesome theme.
Would you be interested to add typescript support to it ?
This is the area I feel comfortable with.

Would you be interested in this kind of contribution ?

**Comment by akzhy** [comment]
Hey, thanks and typescript support is in my to-do list. I will add it as soon as I get time.

**Comment by baart1989** [comment]
would you need a help ?

**Comment by akzhy** [comment]
Hey, any help is appreciated, if you can, just create a PR. 😄
