### ISSUE TITLE
Suggestion: Link back to this github repo!

### ISSUE THREAD

**Issue by r-i-c-h** [akzhy/gatsby-starter-elemental#3]
Was looking at preview site. Had to go to Google to find this repo again... Maybe add a link back here in the about section? Otherwise, nice design! Cheers!

**Comment by akzhy** [comment]
Hey, thanks, I will be adding it (preferably in the footer) but that requires some changes in code. So anyway I will probably add it at the end of the week.

**Comment by akzhy** [comment]
@r-i-c-h Hey, a GitHub link has been added to the footer, and a few other changes have also been made
