### ISSUE TITLE
Disqus comments are not visible in light mode

### ISSUE THREAD

**Issue by sanjithpk** [akzhy/gatsby-starter-elemental#32]
![image](https://user-images.githubusercontent.com/40496139/87566106-28573800-c6e0-11ea-9a9f-56553ea173ee.png)

Browser: Chrome

**Comment by ahmad-reza619** [comment]
Hi @sanjithpk are you using the latest version of this gatsby starter?

**Comment by ahmad-reza619** [comment]
i haven't tried the latest version, but in v1 it's working properly, and i just opened https://elemental.netlify.app. and it seems it's not happened there, can you tell us your chrome version?

**Comment by sanjithpk** [comment]
I'm using the latest version of the elemental starter.

My chrome version is: 83.0.4103.116 (Official Build) (64-bit)

**Comment by akzhy** [comment]
Hey @sanjithpk this issue occurs when you switch the theme after load. ie if you were initially on dark mode and then change to light, Disqus will keep using the light mode until the browser window is refreshed. 
I will try to create an update that solves the issue by refreshing Disqus when the theme is changed.

**Comment by akzhy** [comment]
Hey @sanjithpk check #33  should fix it

**Comment by sanjithpk** [comment]
@akzhy , yes it works! 
Thanks
