### ISSUE TITLE
Unable to Install Starter

### ISSUE THREAD

**Issue by Pulchritude1** [akzhy/gatsby-starter-elemental#38]
It appears not possible to install this starter in its current form. This has been attempted on multiple devices, with multiple people. When 'gatsby develop' is run, this error is shown: ![Issue](https://user-images.githubusercontent.com/91395116/134787514-2224982e-0756-422a-9ddd-05effbf63316.png)

Steps to Reproduce:

Given Node.js and Git are installed...

>npm install -g gatsby-cli
>gatsby new project-name https://github.com/akzhy/gatsby-starter-elemental
>cd project-name
>gatsby develop

**Comment by akzhy** [comment]
Hey could you try it by

```
git clone https://github.com/akzhy/gatsby-starter-elemental
cd gatsby-starter-elemental
yarn
yarn develop
```

**Comment by Pulchritude1** [comment]
>git clone https://github.com/akzhy/gatsby-starter-elemental
>cd gatsby-starter-elemental
>npm install -g yarn
>yarn
>yarn develop

This solution worked well, thanks a lot!

**Comment by Pulchritude1** [comment]
Seemingly unrelated to this, when I locally run the starter, it doesn't seem as thought the front page of the starter is affected by any of my changes to config.ts. While editing other files result in changes in the corresponding page, editing config.ts doesn't lead to the same change.

**Comment by akzhy** [comment]
Did you try restarting the dev process?

**Comment by Pulchritude1** [comment]
Yes, I've tried this and it still does not work. I've also replicated the issue on different devices.

**Comment by Pulchritude1** [comment]
Are you able to edit config.ts and see a change in the site?

**Comment by Pulchritude1** [comment]
> Did you try restarting the dev process?

I have now. Thank you. I previously interpreted what you said to be reinstalling the starter, I now realise that you meant rerunning the server. I stopped running it in the browser, made a change, and reran it, and it worked perfectly, thanks.
