### ISSUE TITLE
Netlify forms

### ISSUE THREAD

**Issue by ngehlert** [akzhy/gatsby-starter-elemental#9]
is there a way to hook up the contact form to netlify? When I try to set the following things on the form the form still tries to make a post request to `/contact` which fails with a 404

```
    <form
        method="post"
        data-netlify="true"
        name="contact-form"
    >
```

**Comment by akzhy** [comment]
Hey, I haven't tried it with netlify, I will test it out and send you an update.

**Comment by akzhy** [comment]
@ngehlert Hey, I haven't tried it with netlify, I will test it out and send you an update.

**Comment by akzhy** [comment]
Hi @ngehlert , 
I've created a branch that supports netlify forms. Check branch `netlify-form` for the code. You can replace the `src/components/contact.js` to make it work.

Check pull #10 for demo.

**Comment by ngehlert** [comment]
awesome thanks. will try this week and review the PR

**Comment by ahmad-reza619** [comment]
@akzhy this is a nice addition, but there is no documentation on how to's. and also is this going to be merged to master?

**Comment by akzhy** [comment]
@ahmad-reza619 Hey, I did not merge it to master because Netlify has a different response compared to other services. I think perhaps it is better to add the file as contact-netlify, so that netlify users can replace it with the default one.

**Comment by ahmad-reza619** [comment]
yes, that would be helpful 😄

**Comment by ahmad-reza619** [comment]
well, i think maybe we can add description in the readme file, so that anyone who use this template and also using netlify could easily replace the default 🤔
